In [22]:
import numpy as np

1. Что надо изменить в последнем примере, чтобы он заработал без ошибок (транслирование)?

In [23]:
""" a = np.ones((3, 2))
b = np.arange(3)

# 2 (3, 2)   (3, 2)    (3, 2)
# 1 (3, ) -> (1, 3) -> (3, 3)

c = a + b """

a = np.ones((3, 2))
b = np.arange(3)

print(a)
print(b)

b = b[:, np.newaxis]

c = a + b
print(c)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]
[[1. 1.]
 [2. 2.]
 [3. 3.]]


2. Пример для y. Вычислить количество элементов (по обоим размерностям), значения которых больше 3 и меньше 9

In [24]:
y = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

c = (y > 3) & (y < 9)
count = np.sum(c)

print(count)

5
