In [288]:
import numpy as np
import pandas as pd

Pandas - расширение NumPy (структурированные массивы). Строки и столбцы индексируются метками, а не только числовыми значениями

Series, DataFrame, Index

Series

In [289]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)
print(type(data))

print(data.values)
print(type(data.values))

print(data.index)
print(type(data.index))


0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
<class 'pandas.core.series.Series'>
[0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=4, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>


In [290]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data[0])
print(data[1:3])

data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
print(data)
print(data['a'])
print(data['b': 'd'])

print(type(data.index))

0.25
1    0.50
2    0.75
dtype: float64
a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.25
b    0.50
c    0.75
d    1.00
dtype: float64
<class 'pandas.core.indexes.base.Index'>


In [291]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1, 10, 7, 'd'])

print(data)

print(data[1])
print(data[10: 'd'])

1     0.25
10    0.50
7     0.75
d     1.00
dtype: float64
0.25
10    0.50
7     0.75
d     1.00
dtype: float64


In [292]:
population_dict = {
    'city1': 1001,
    'city2': 1002,
    'city3': 1003,
    'city4': 1004,
    'city5': 1005,
}

population = pd.Series(population_dict)
print(population)

print(population['city4'])
print(population['city4': 'city5'])

city1    1001
city2    1002
city3    1003
city4    1004
city5    1005
dtype: int64
1004
city4    1004
city5    1005
dtype: int64


Для создания Series можно использовать 
1. Списки Python или массивы NumPy
2. Скалярные значения
3. Словари

DataFrame - двумерный массив с явно определенными индексами. Последовательность согласованных по индексам объектов Series

In [293]:
population_dict = {
    'city1': 1001,
    'city2': 1002,
    'city3': 1003,
    'city4': 1004,
    'city5': 1005,
}

area_dict = {
    'city1': 9991,
    'city2': 9992,
    'city3': 9993,
    'city4': 9994,
    'city5': 9995,
}

population = pd.Series(population_dict)
area = pd.Series(area_dict)

""" print(population)
print(area) """

states = pd.DataFrame({
    'population1': population,
    'area1': area,
})

print(states)

print(states.values)
print(states.index)
print(states.columns)

print(type(states.values))
print(type(states.index))
print(type(states.columns))

       population1  area1
city1         1001   9991
city2         1002   9992
city3         1003   9993
city4         1004   9994
city5         1005   9995
[[1001 9991]
 [1002 9992]
 [1003 9993]
 [1004 9994]
 [1005 9995]]
Index(['city1', 'city2', 'city3', 'city4', 'city5'], dtype='object')
Index(['population1', 'area1'], dtype='object')
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.base.Index'>


In [294]:
print(states['area1'])

city1    9991
city2    9992
city3    9993
city4    9994
city5    9995
Name: area1, dtype: int64


DataFrame. Способы создания
1. Объекты Series
2. Списки словарей
3. Словари объектов  Series
4. Двумерный массив NumPy
5. Структурированный массив NumPy

Index - способ организации ссылки на данные объектов Series и DataFrame. Index - неизменяем, упорядочен, является мультимножеством (могут быть повторяющиеся значения)

In [295]:
ind = pd.Index([2, 3, 5, 7, 11])
print(ind[1])
print(ind[::2])

""" ind[1] = 5 """ # Нельзя!!

3
Index([2, 5, 11], dtype='int64')


' ind[1] = 5 '

Index - следует соглашениям объекта set (python)

In [296]:
indA = pd.Index([1, 2, 3, 4, 5])
indB = pd.Index([2, 3, 4, 5, 6])

print(indA.intersection(indB))

Index([2, 3, 4, 5], dtype='int64')


Выборка данных из Series


Как словарь

In [297]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

print('a' in data)
print('z' in data)

print(data.keys())

print(list(data.items()))

data['a'] = 100
data['z'] = 1000

print(data)

True
False
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]
a     100.00
b       0.50
c       0.75
d       1.00
z    1000.00
dtype: float64


Как одномерный массив

In [298]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

print(data['a': 'c'])
print(data[0:2])
print(data[(data > 0.5)  & (data < 1)])
print(data[['a', 'd']])

data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1, 3, 10, 15])

print(data[1])

a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
dtype: float64
c    0.75
dtype: float64
a    0.25
d    1.00
dtype: float64
0.25


Атрибуты-индексаторы

In [299]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1, 3, 10, 15])

print(data[1])

print(data.loc[1])
print(data.iloc[1])

0.25
0.25
0.5


Выборка данных из DataFrame

Как словарь

In [300]:
pop = pd.Series(
    {
        'city1': 1001,
        'city2': 1002,
        'city3': 1003,
        'city4': 1004,
        'city5': 1005,
    }
)

area = pd.Series(
    {
        'city1': 9991,
        'city2': 9992,
        'city3': 9993,
        'city4': 9994,
        'city5': 9995,
    }
)

data = pd.DataFrame({'area1': area, 'pop1': pop, 'pop': pop})

print(data)

print(data['area1'])
print(data.area1)

print(data.pop1 is data['pop1'])
print(data.pop is data['pop1'])

data['new'] = data['area1']

data['new'] = data['area1'] / data['pop1']

print(data)

       area1  pop1   pop
city1   9991  1001  1001
city2   9992  1002  1002
city3   9993  1003  1003
city4   9994  1004  1004
city5   9995  1005  1005
city1    9991
city2    9992
city3    9993
city4    9994
city5    9995
Name: area1, dtype: int64
city1    9991
city2    9992
city3    9993
city4    9994
city5    9995
Name: area1, dtype: int64
True
False
       area1  pop1   pop       new
city1   9991  1001  1001  9.981019
city2   9992  1002  1002  9.972056
city3   9993  1003  1003  9.963111
city4   9994  1004  1004  9.954183
city5   9995  1005  1005  9.945274


Двумерный NumPy массив

In [301]:
pop = pd.Series(
    {
        'city1': 1001,
        'city2': 1002,
        'city3': 1003,
        'city4': 1004,
        'city5': 1005,
    }
)

area = pd.Series(
    {
        'city1': 9991,
        'city2': 9992,
        'city3': 9993,
        'city4': 9994,
        'city5': 9995,
    }
)

data = pd.DataFrame({'area1': area, 'pop1': pop})

print(data)

print(data.values)

print(data.T)

print(data['area1'])

print(data.values[0: 3])

       area1  pop1
city1   9991  1001
city2   9992  1002
city3   9993  1003
city4   9994  1004
city5   9995  1005
[[9991 1001]
 [9992 1002]
 [9993 1003]
 [9994 1004]
 [9995 1005]]
       city1  city2  city3  city4  city5
area1   9991   9992   9993   9994   9995
pop1    1001   1002   1003   1004   1005
city1    9991
city2    9992
city3    9993
city4    9994
city5    9995
Name: area1, dtype: int64
[[9991 1001]
 [9992 1002]
 [9993 1003]]


Атрибуты-индексаторы

In [302]:
pop = pd.Series(
    {
        'city1': 1001,
        'city2': 1002,
        'city3': 1003,
        'city4': 1004,
        'city5': 1005,
    }
)

area = pd.Series(
    {
        'city1': 9991,
        'city2': 9992,
        'city3': 9993,
        'city4': 9994,
        'city5': 9995,
    }
)

data = pd.DataFrame({'area1': area, 'pop1': pop, 'pop': pop})

print(data)
print(data.iloc[:3, 1: 2])
print(data.loc[: 'city4', 'pop1': 'pop'])
print(data.loc[data['pop'] > 1002, ['area1', 'pop']])

data.iloc[0, 2] = 9999

print(data)

       area1  pop1   pop
city1   9991  1001  1001
city2   9992  1002  1002
city3   9993  1003  1003
city4   9994  1004  1004
city5   9995  1005  1005
       pop1
city1  1001
city2  1002
city3  1003
       pop1   pop
city1  1001  1001
city2  1002  1002
city3  1003  1003
city4  1004  1004
       area1   pop
city3   9993  1003
city4   9994  1004
city5   9995  1005
       area1  pop1   pop
city1   9991  1001  9999
city2   9992  1002  1002
city3   9993  1003  1003
city4   9994  1004  1004
city5   9995  1005  1005


In [303]:
rng = np.random.default_rng()
s = pd.Series(rng.integers(0, 10, 4))

print(s)
print(np.exp(s))

0    5
1    1
2    1
3    1
dtype: int64
0    148.413159
1      2.718282
2      2.718282
3      2.718282
dtype: float64


In [304]:
pop = pd.Series(
    {
        'city1': 1001,
        'city2': 1002,
        'city3': 1003,
        'city41': 1004,
        'city51': 1005,
    }
)

area = pd.Series(
    {
        'city1': 9991,
        'city2': 9992,
        'city3': 9993,
        'city42': 9994,
        'city52': 9995,
    }
)

data = pd.DataFrame({'area1': area, 'pop1': pop})

print(data)

         area1    pop1
city1   9991.0  1001.0
city2   9992.0  1002.0
city3   9993.0  1003.0
city41     NaN  1004.0
city42  9994.0     NaN
city51     NaN  1005.0
city52  9995.0     NaN


NaN - not a number

In [305]:
rng = np.random.default_rng()

dfA = pd.DataFrame(rng.integers(0, 10, (2, 2)), columns=['a', 'b'])
dfB = pd.DataFrame(rng.integers(0, 10, (3, 3)), columns=['a', 'b', 'c'])

print(dfA)
print(dfB)

print(dfA + dfB)

   a  b
0  9  1
1  8  8
   a  b  c
0  5  7  2
1  6  8  9
2  8  6  9
      a     b   c
0  14.0   8.0 NaN
1  14.0  16.0 NaN
2   NaN   NaN NaN


In [306]:
rng = np.random.default_rng()

A = rng.integers(0, 10, (3, 4))

print(A)

print(A[0])
print(A - A[0])

[[9 8 9 8]
 [0 8 7 5]
 [0 6 6 0]]
[9 8 9 8]
[[ 0  0  0  0]
 [-9  0 -2 -3]
 [-9 -2 -3 -8]]


In [307]:
rng = np.random.default_rng()

A = rng.integers(0, 10, (3, 4))

print(A)

df = pd.DataFrame(A, columns=['a', 'b', 'c', 'd'])
print(df)

print(df.iloc[0])
print(df - df.iloc[0])

print(df.iloc[0, ::2])
print(df - df.iloc[0, ::2])

[[0 8 8 0]
 [4 2 2 1]
 [7 0 1 3]]
   a  b  c  d
0  0  8  8  0
1  4  2  2  1
2  7  0  1  3
a    0
b    8
c    8
d    0
Name: 0, dtype: int64
   a  b  c  d
0  0  0  0  0
1  4 -6 -6  1
2  7 -8 -7  3
a    0
c    8
Name: 0, dtype: int64
     a   b    c   d
0  0.0 NaN  0.0 NaN
1  4.0 NaN -6.0 NaN
2  7.0 NaN -7.0 NaN


NA - значения: NaN, null, -99999

Pandas. Два способа хранения отсутствующих значений
1. Индикаторы NaN, None
2. null

None - объект (накладные расходы). Не работает с sum, min...

In [308]:
val1 = np.array([1, 2, 3])
print(val1.sum())

""" val1 = np.array([1, None, 2, 3])
print(val1.sum()) """ # Не работает

val1 = np.array([1, np.nan, 2, 3])
print(val1)
print(val1.sum())
print(np.nansum(val1))

6
[ 1. nan  2.  3.]
nan
6.0


In [ ]:
x = pd.Series(range(5), dtype=int)
print(x)

x[0] = None
x[1] = np.nan
print(x)

x1 = pd.Series(['a', 'b', 'c', 'd'])
print(x1)

x1[0] = None
x1[1] = np.nan

print(x1)

0    0
1    1
2    2
3    3
4    4
dtype: int32
0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
dtype: float64
0    a
1    b
2    c
3    d
dtype: object
0    None
1     NaN
2       c
3       d
dtype: object


In [310]:
x2 = pd.Series([1, 2, 3, np.nan, None, pd.NA])
print(x2)

x3 = pd.Series([1, 2, 3, np.nan, None, pd.NA], dtype='Int32')
print(x3)

print(x3.isnull())
print(x3[x3.isnull()])
print(x3[x3.notnull()])

0       1
1       2
2       3
3     NaN
4    None
5    <NA>
dtype: object
0       1
1       2
2       3
3    <NA>
4    <NA>
5    <NA>
dtype: Int32
0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool
3    <NA>
4    <NA>
5    <NA>
dtype: Int32
0    1
1    2
2    3
dtype: Int32


In [311]:
print(x3.dropna())

df = pd.DataFrame(
    [
        [1, 2, 3, np.nan, None, pd.NA],
        [1, 2, 3, None, 5, 6],
        [1, np.nan, 3, None, np.nan, 6],
    ]
)

print(df)
print()
print(df.dropna())
print()
print(df.dropna(axis=0))
print()
print(df.dropna(axis=1))

0    1
1    2
2    3
dtype: Int32
   0    1  2   3    4     5
0  1  2.0  3 NaN  NaN  <NA>
1  1  2.0  3 NaN  5.0     6
2  1  NaN  3 NaN  NaN     6

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5]
Index: []

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5]
Index: []

   0  2
0  1  3
1  1  3
2  1  3


how

1. all - все значения NA
2. any - хотя бы одно значение
3. thresh = x, остается, если присутствует МИНИМУМ x НЕПУСТЫХ значений

In [312]:
print(df.dropna(axis=1, how='all'))
print(df.dropna(axis=1, how='any'))
print(df.dropna(axis=1, thresh=2))

   0    1  2    4     5
0  1  2.0  3  NaN  <NA>
1  1  2.0  3  5.0     6
2  1  NaN  3  NaN     6
   0  2
0  1  3
1  1  3
2  1  3
   0    1  2     5
0  1  2.0  3  <NA>
1  1  2.0  3     6
2  1  NaN  3     6
